Dzcover/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from user_app import views as user
# from search_app import views as search
from django.contrib.auth import views as auth_views



urlpatterns = [
    url(r'^$', user.Login.as_view(), name= 'index'),
    url(r'^signup/$', user.signup, name='signup'),
    url(r'^signup/confirm$', user.signup_confirm_message, name='signup_confirm_message'),
    url(r'^admin/', admin.site.urls),
    url(r'^register/username/$', user.check_username, name='check_username'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        user.ActivateLinkView.as_view(), name='activate'),
    url(r'^resend/activation/$', user.resend_activate_link, name='resend_activation'),
    url(r'^logout/$', user.user_log_out, name='logout'),
    url(r'^view/(?P<username>\w+)/$', user.view_user, name='view_user'),
    url(r'^view/(?P<username>\w+)/network/$', user.view_network, name='view_network'),
    url(r'^view/(?P<username>\w+)/recommendation/$', user.RecommendedView.as_view(), name='view_recommended'),
    url(r'^network/delete/(?P<username>\w+)/$', user.remove_network, name='remove_network'),
    url(r'^job/', include('job_app.urls', namespace='job')),
    url(r'^people/$', user.DiscoverPeople.as_view(), name='discover_people'),
    url(r'^notifications/$', user.NotificationView.as_view(), name='notifications'),
    url(r'^quicksearch/$', user.quick_search, name='quick_search'),
    url(r'^poll/updates/$' ,user.poll_updates, name='poll_updates'),
    url(r'^request/accept/(?P<username>\w+)/$' ,user.accept_request, name='accept_request'),
    url(r'^request/decline/(?P<username>\w+)/$' ,user.decline_request, name= 'decline_request'),
    url(r'^request/send/(?P<username>\w+)/$' ,user.send_request, name='send_request'),
    url(r'^recommend/(?P<username>\w+)/$' ,user.recommend_user, name='recommend_action'),
    url(r'^request/remove/(?P<username>\w+)/$' ,user.remove_request, name='delete_request'),
    url(r'^edit/profile/$', user.EditProfile.as_view(), name='profile_edit'),
    url(r'^view/(?P<username>\w+)/album/', include('album_app.urls', namespace='album')),
    url(r'^view/(?P<username>\w+)/notes/', include('notes_app.urls', namespace='notes')),
    url(r'^view/(?P<username>\w+)/about-me/', user.about_me, name='about_me'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^about/$', user.help, name='help'),
    url(r'^privacy/$', user.privacy, name='privacy'),
    url(r'^cookies/$', user.cookies, name='cookies'),
    url(r'^view/(?P<username>\w+)/account/$', user.view_account, name='view_account'),
    url(r'^(?P<username>\w+)/account/delete/$', user.delete_account, name='delete_account'),
    url(r'^terms-and-conditions/$', user.terms_and_condition, name='terms')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job_app/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    url(r'^feed/$', views.job_feed, name= 'feed'),
    url(r'^guide/$', views.job_post_guide, name= 'guide'),
    url(r'^posted/(?P<username>\w+)$', views.view_posted_jobs, name= 'posted'),
    url(r'^create/$', views.CreateJob.as_view(), name= 'create'),
    url(r'^delete/$', views.delete_posted_job, name='delete_job'),
    url(r'^edit/(?P<job_id>\w+)/$', views.JobEdit.as_view(), name= 'edit'),
    url(r'^view/(?P<slug>[-\w\d]+),(?P<job_id>\w+)$', views.view_job, name= 'view_job'),
    url(r'^search/$', views.JobList.as_view(), name='discover_jobs'),
]

job_app/forms.py
from django.forms import ModelForm
from django import forms
from .models import Job
from datetime import date


class JobPostForm(ModelForm):
    job_type_choices = (('Full-time', 'Full-time'),('Part-time', 'Part-time'),('Coop/Intern', 'Coop/Intern'),('Voluntuary', 'Voluntuary'))
    company_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Company name'}))
    profession = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Profession'}))
    position = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Position'}))
    job_type = forms.ChoiceField(widget=forms.Select(), choices = job_type_choices, label = 'Job Type')
    link = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Link'}),  required = False)
    city = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'City', 'autocomplete':'off'}))
    expiry_day = forms.IntegerField(min_value = 7, max_value = 90,widget=forms.NumberInput(attrs={'placeholder': 'number'}))
    about_company = forms.CharField(widget= forms.Textarea(attrs={'rows':'10', 'data-min-rows': '10', 'class':'autoExpand'}),label='About your company', max_length= 1000)
    description = forms.CharField(widget= forms.Textarea(attrs={'rows':'10', 'data-min-rows': '10', 'class':'autoExpand'}),label='Description*', max_length= 5000)
    qualification = forms.CharField(widget= forms.Textarea(attrs={'rows':'10', 'data-min-rows': '10', 'class':'autoExpand'}),label='Qualification', max_length= 5000)
    more_info = forms.CharField(widget= forms.Textarea(attrs={'rows':'5', 'data-min-rows': '5', 'class':'autoExpand','placeholder':'optional'}),label='More Info', max_length= 1500, required= False)
    class Meta:
        model = Job;
        fields = ['company_name', 'profession', 'position','description','about_company',

        'qualification','city','link','job_type', 'more_info']

class JobEditForm(ModelForm):
    job_type_choices = (('Full-time', 'Full-time'),('Part-time', 'Part-time'),('Coop/Intern', 'Coop/Intern'),('Voluntuary', 'Voluntuary'))
    company_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Company name'}))
    profession = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Profession'}))
    position = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Position'}))
    job_type = forms.ChoiceField(widget=forms.Select(), choices = job_type_choices, label = 'Job Type')
    link = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Link', 'autocomplete':'off'}),  required = False)
    city = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'City'}))
    about_company = forms.CharField(widget= forms.Textarea(attrs={'rows':'10', 'data-min-rows': '10', 'class':'autoExpand'}),label='About your company', max_length= 1000)
    description = forms.CharField(widget= forms.Textarea(attrs={'rows':'10', 'data-min-rows': '10', 'class':'autoExpand'}),label='Description*', max_length= 5000)
    qualification = forms.CharField(widget= forms.Textarea(attrs={'rows':'10', 'data-min-rows': '10', 'class':'autoExpand'}),label='Qualification', max_length= 5000)
    more_info = forms.CharField(widget= forms.Textarea(attrs={'rows':'5', 'data-min-rows': '5', 'class':'autoExpand','placeholder':'optional'}),label='More Info', max_length= 1500, required= False)
    class Meta:
        model = Job;
        fields = ['company_name', 'profession', 'position','description','about_company',
        'qualification','city','link','job_type', 'more_info']


class JobSearchForm(ModelForm):
    job_type_choices = (('All', 'All'),('Full-time', 'Full-time'),('Part-time', 'Part-time'),('Coop/Intern', 'Coop/Intern'),('Voluntuary', 'Voluntuary'))
    search= forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Search for Job','class':'form-control'}))
    city = forms.CharField(widget=forms.TextInput(attrs={'autocomplete':'off',}), required = False)
    job_type = forms.ChoiceField(widget = forms.Select(), choices = job_type_choices, label='Type')

    class Meta:
        model = Job;
        fields = ['city', 'job_type']


templates/job/all_jobs.html
<div class='job-card-container'>
<ul >


   {% for job in jobs %}

   <li class='job-card' data-job-id ='{{job.id}}'>
       <p class= 'job-header' >
         <a href='{{job.get_absolute_url}}'><strong> {{job}} </strong></a>
       </p>
       <p class='job-content'><strong>Company:</strong> {{job.company_name}}</p>
       <p class='job-content'><strong>Location:</strong> {{job.get_location}}</p>
       <p class='job-content'><strong>Type:</strong> {{job.job_type}}</p>
       <p class='job-meta'>posted {{job.created_on|date}} by <a href='{{job.user.get_absolute_url}}'>{{job.user.get_full_name}}</a></p>
   </li>
   {% endfor %}
 <ul class="pagination center-block text-center">
    {% if people.paginator.num_pages > 1 %}
     <span class="step-links custom-step-links">
       {% if jobs.has_previous %}
       <a class='btn page-previous' href="?search={{request.GET.search}}&amp;state_and_country={{request.GET.state_and_country}}&amp;city={{request.GET.city}}&amp;job_type={{request.GET.job_type}}&amp;page={{ jobs.previous_page_number }}">previous</a>
       {% endif %}
       {% if jobs.has_next %}
       <a class='btn-sm btn page-next' href="?search={{request.GET.search}}&amp;state_and_country={{request.GET.state_and_country}}&amp;city={{request.GET.city}}&amp;job_type={{request.GET.job_type}}&amp;page={{ jobs.next_page_number }}">next</a>
       {% endif %}
     </span>
     {% endif %}
 </ul>
</ul>
</div>

templates/job/create_job.html
{% extends 'users/container.html'%}
{% load static from staticfiles%}

{% block mainarticle %}
<div class='col-sm-8 col-sm-offset-2'>
  <p> Brief Article: <a>Posting jobs on Dzcover</a> <i class='icon ion-ios-book-outline'></i></p>
  <hr>
  <form class='job-form' action='' method='post'>
  {% csrf_token %}
  {{ form.non_field_errors}}
  <div class='row'>
    <div class='col-sm-4'>
        <div class="fieldWrapper fieldInput">
              {{ form.company_name.errors }}
              {{ form.company_name.label_tag}}
              {{ form.company_name }}
          </div>
          </div>
          <div class='col-sm-4'>
                <div class="fieldWrapper fieldInput">
                    {{ form.profession.errors }}
                    {{ form.profession.label_tag}}
                    {{ form.profession }}
                </div>
          </div>
          <div class='col-sm-4'>
                <div class="fieldWrapper fieldInput">
                    {{ form.position.errors }}
                    {{ form.position.label_tag}}
                    {{ form.position }}
                </div>
          </div>
          </div>

          <div class='row'>
          <div class='col-sm-4'>
                <div class="fieldWrapper fieldInput">
                    {{ form.city.errors }}
                    {{ form.city.label_tag}}
                    {{ form.city }}
                </div>
          </div>
          <div class='col-sm-4'>
                <div class="fieldWrapper fieldInput">
                    {{ form.job_type.errors }}
                    {{ form.job_type.label_tag}}
                    {{ form.job_type }}
                </div>
          </div>
          </div>

         <div class='row'>
          <div class='col-sm-12'>
                <div class="fieldWrapper fieldInput">
                    {{ form.about_company.errors }}
                    {{ form.about_company.label_tag}}
                    {{ form.about_company }}
                </div>
          </div>
        </div>	  

          <div class='row'>
          <div class='col-sm-12'>
            <div class="fieldWrapper">
                {{ form.description.errors }}
                {{ form.description.label_tag}}
                {{ form.description }}

            </div>
          </div>
          </div>

          <div class='row'>
          <div class='col-sm-12'>
              <div class="fieldWrapper">
                  {{ form.qualification.errors }}
                  {{ form.qualification.label_tag}}
                  {{ form.qualification }}
              </div>
          </div>
          </div>

          <div class='row'>
          <div class='col-sm-6'>
              <div class="fieldWrapper fieldInput">
                  {{ form.more_info.errors }}
                  {{ form.more_info.label_tag}}
                  {{ form.more_info }}
              </div>
          </div>
          </div>

          <div class='row'>
          <div class='col-xs-6'>
              <div class="fieldWrapper fieldInput">
                  {{ form.link.errors }}
                  {{ form.link.label_tag}}
                  {{ form.link }}
              </div>
          </div>
          </div>

        <div class='fieldWrapper col-sm-12'>
          {{form.expiry_day.errors}}
          {{form.expiry_day.label_tag}}
          <h6>Type/select the number of days your job posting should last. We allow job posting with a minimum of a week(7) till 90 days.
          You can always delete the post from your page when the right candidate has been found</h6>
          <div class='row'>
          <div class='col-xs-4 col-sm-2'>
          {{form.expiry_day}} <p class='text-left'> days</span>
          </div>
          </div>
        </div>



          <br>
          <button class='btn btn-default center-block'> Submit </button>
        </form>
        <br>
      </div>
</div>
{% endblock %}
{% block javascript %}
<script>
new TeleportAutocomplete({ el: '#id_city', maxItems: 5 });
</script>
  {%endblock%}

templates/job/discover_jobs.html
{% extends 'users/container.html'%}
{% load static from staticfiles%}

{% block mainarticle %}
<div class='row'>
  <h3 class='text-center discover-title'>  Discover Jobs </h3>
<div class='col-md-12'>
 <div class='col-md-3'>
    <form class='job-search-form' action='' method = 'get'>
      {{form.non_field_errors}}
      <div class='row'>
       
          <div class='col-xs-8 col-md-12'>
            <div class="fieldWrapper">
              {{ form.city.errors }}
              {{ form.city.label_tag}}
              {{ form.city }}
            </div>
        </div>
        <div class='col-xs-4 col-md-12 '>
          <div class="fieldWrapper filter-jobs">
              {{ form.job_type.errors }}
              {{ form.job_type.label_tag}}
              {{ form.job_type }}
            </div>
        </div>
      </div>
      <div class='row'>
        <br>
        <div class='col-xs-12 col-sm-12'>
            <div class="fieldWrapper form-group form-inline">
              <div class="input-group">
              {{ form.search.errors }}
              {{ form.search }}
              <div class="input-group-btn">
                <button class='btn btn-default btn-sm' type="submit" >
                  <svg  xmlns="http://www.w3.org/2000/svg" width="512px" height="512px"  class='ion ion-18' viewBox="0 0 512 512"  id='ion-search'>
                      <g>
                  <path d="M445 386.7l-84.8-85.9c13.8-24.1 21-50.9 21-77.9C381.2 135.3 310 64 222.6 64 135.2 64 64 135.3 64 222.9c0 87.6 71.2 158.9 158.6 158.9 27.9 0 55.5-7.7 80.1-22.4l84.4 85.6c1.9 1.9 4.6 3.1 7.3 3.1s5.4-1.1 7.3-3.1l43.3-43.8c4-4.1 4-10.5 0-14.5zM222.6 125.9c53.4 0 96.8 43.5 96.8 97s-43.4 97-96.8 97-96.8-43.5-96.8-97 43.4-97 96.8-97z"></path>
                </svg>
              </button>
              </div>
            </div>
            </div>
          </div>
        </div>

    </form>
  </div>

  <div class='col-md-6 search-result'>

   {% if request.GET.search %}
   <h6 class='center-block text-center'><strong> Showing '{{request.GET.job_type}}' Jobs found  for '{{request.GET.search}}'</strong></h6>
   <p class='text-right job-meta'>Found {{total}}</p>
   {% endif %}
     {% if jobs %}
          {% include 'job/all_jobs.html'%}
    {% endif %}
    </div>
  <div class='col-md-3 '>
    <div class='job-feed-container'>

    <h4><i class="icon ion-radio-waves ion-custom-24"></i> Job Feed</h4>

    {% if job_feed %}
      <ul class='list-unstyled'>
       {% for job in job_feed %}
       <li class='job-mini-card' data-job-id ='{{job.id}}'>
          <p><a href='{{job.user.get_absolute_url}}' target='_blank'>{{job.user.get_full_name}} </a> posted a job <b>{{job.created_on|date}}</b></p>
           <p class= 'job-mini-card-header' >
             <a href='{{job.get_absolute_url}}' target='_blank'><strong> {{job}} </strong></a> <span class='job-card-location'> {{job.city}}, {{job.state_and_country}}.</span>
           </p>
           <p><strong>Company:</strong> {{job.company_name}}</p>
       </li>
       {% endfor %}
         <a href = '{% url "job:feed" %}' class='mini-link'>  View All <i class="icon ion-ios-arrow-thin-right"></i></a>
     </ul>
     {% else %}
    <p> No Jobs from your network </p>
     {% endif %}
  </div>
</div>
  </div>
</div>

{% endblock %}
{% block javascript %}
<script>
new TeleportAutocomplete({ el: '#id_city', maxItems: 5 });
</script>


{% endblock %}

templates/job/job_edit.html
{% extends 'users/container.html'%}
{% load static from staticfiles%}

{% block mainarticle %}
<div class='row'>
  <br>
<div class='col-xs-10 col-xs-offset-1 col-md-8 col-md-offset-2'>
    <h4> Edit Job</h4>
    <hr>
    <form class='job-form' action='' method='post'>
      {% csrf_token %}
      {{ form.non_field_errors}}
    <div class='row'>
      <div class='col-xs-6 col-sm-4'>
                        <div class="fieldWrapper fieldInput">
                            {{ form.company_name.errors }}
                            {{ form.company_name.label_tag}}
                            {{ form.company_name }}
                        </div>
      </div>
      <div class='col-xs-6 col-sm-4'>
                        <div class="fieldWrapper fieldInput">
                            {{ form.profession.errors }}
                            {{ form.profession.label_tag}}
                            {{ form.profession }}
                        </div>
      </div>
      <div class='col-xs-6 col-sm-4'>
                        <div class="fieldWrapper fieldInput">
                            {{ form.position.errors }}
                            {{ form.position.label_tag}}
                            {{ form.position }}
                        </div>
      </div>
    </div>

    <div class='row'>
      <div class='col-xs-6 col-sm-4'>
                        <div class="fieldWrapper fieldInput">
                            {{ form.state_and_country.errors }}
                            {{ form.state_and_country.label_tag}}
                            {{ form.state_and_country }}
                        </div>
      </div>
      <div class='col-xs-6 col-sm-4'>
                        <div class="fieldWrapper fieldInput">
                            {{ form.city.errors }}
                            {{ form.city.label_tag}}
                            {{ form.city }}
                        </div>
      </div>
      <div class='col-xs-6 col-sm-4'>
                        <div class="fieldWrapper fieldInput">
                            {{ form.job_type.errors }}
                            {{ form.job_type.label_tag}}
                            {{ form.job_type }}
                        </div>
      </div>
    </div>

    <div class='row'>
    <div class='col-sm-12'>
          <div class="fieldWrapper fieldInput">
              {{ form.about_company.errors }}
              {{ form.about_company.label_tag}}
              {{ form.about_company }}
          </div>
    </div>
   </div>


    <div class='row'>
      <div class='col-xs-12 col-md-12'>
                      <div class="fieldWrapper">
                          {{ form.description.errors }}
                          {{ form.description.label_tag}}
                          {{ form.description }}

                      </div>
    </div>
  </div>

    <div class='row'>
      <div class='col-xs-12 col-md-12'>
                      <div class="fieldWrapper">
                          {{ form.qualification.errors }}
                          {{ form.qualification.label_tag}}
                          {{ form.qualification }}
                      </div>
      </div>
    </div>

    <div class='row'>
      <div class='col-xs-12 col-md-6'>
                      <div class="fieldWrapper fieldInput">
                          {{ form.more_info.errors }}
                          {{ form.more_info.label_tag}}
                          {{ form.more_info }}
                      </div>
      </div>
    </div>

    <div class='row'>
      <div class='col-xs-6 col-md-6'>
                      <div class="fieldWrapper fieldInput">
                          {{ form.link.errors }}
                          {{ form.link.label_tag}}
                          {{ form.link }}
                      </div>
      </div>
    </div>


    <button type='submit' class='btn btn-default btn-sm center-block' value='Update'>Update</button>
  </form>

</div>
</div>
</div>
  {%endblock%}

templates/job/job_feed.html
{% extends 'users/container.html'%}
{% load static from staticfiles%}

{% block mainarticle %}
  <h4 class='text-center'><i class="icon ion-radio-waves ion-custom-24"></i> Job Feed</h4>
  <div class='col-md-6 col-md-offset-3'>
  <p class='text-left job-meta'>Found {{total}}</p>
  {% if jobs %}
  {% include 'job/all_jobs.html'%}
  {% endif %}
  </div>
{% endblock %}

templates/job/posted_jobs.html
{% extends 'users/portfolio_base.html'%}
{% load static from staticfiles%}
{% block body_tag%} class='jobs' {% endblock%}
{% block portfolio-body %}
<div class='col-md-8 col-md-offset-1'>
  <div class='row center-block text-center'>
  <a href='{% url "job:create"%}'>Post a Job <i class='icon ion-ios-plus-empty'></i></a>
</div>
<br>
{% if posted_jobs %}

     <ul class='job-card-container'>
       <p id='job_count'> Jobs: {{total}} </p>
        {% for job in posted_jobs %}
        <li class='job-card' data-job-id = '{{job.id}}'>
            <p class= 'job-header' >
              <a href='{{job.get_absolute_url}}'><strong> {{job}} </strong> </a>
            </p>
                 <p><strong>Company:</strong> {{job.company_name}}</p>
                 <p><strong>Location:</strong> {{job.get_location}}</p>
                 <p class='info-time'>posted {{job.created_on|date}}</p>
                 {% ifequal job.user request.user %}
                 <div>
                     <a class='btn btn-default btn-sm' href= '{% url "job:edit" job_id=job.id %}'> Edit</a>
                     <a class='btn btn-default btn-sm btn-delete-job-post' > Delete </a>
               </div>
               {% endifequal %}
          </li>
        {% endfor %}
        {% if posted_jobs.paginator.num_pages > 1 %}
        <ul class="pagination center-block text-center">

        <span class="step-links custom-step-links">

          {% if posted_jobs.has_previous %}
          <a class='btn-sm btn page-previous' href="?page={{ posted_jobs.previous_page_number }}"><i class="icon ion-ios-arrow-thin-left"></i> <strong>Prev </steong></a>
          {% endif %}


          {% for page in custom_page_range %}

          {% ifequal posted_jobs.number page %}
          <a class='btn-sm page-number active-page-number' href="?page={{ page}}"> {{page}}</a>
          {% else %}
          <a class='btn-sm page-number' href="?page={{ page }}"> {{page}} </a>
          {% endifequal %}

          {% endfor %}

          {% if posted_jobs.has_next %}
          <a class='btn-sm btn page-next' href="?page={{ posted_jobs.next_page_number }}"><strong>Next </steong><i class="icon ion-ios-arrow-thin-right"></i></a>
          {% endif %}

        </span>
       </ul>
       {% endif %}
     </ul>
     {%else%}
     <p class='text-center'> No Posted jobs </p>
     {% endif %}
  </div>

  <div class='col-md-3 ads-container'>

    <div class='row ads-container'>
      {% include 'ads.html'%}
    </div>
  </div>

  {%endblock%}

templates/job/view_job.html
{% extends 'users/container.html'%}
{% load static from staticfiles%}

{% block mainarticle %}

<div class='col-md-8 col-md-offset-1'>
      <div class='job-card-container'>
           <div class='job-card  view-job-card' data-job-id ='{{job.id}}'>
              <div class= 'job-header' >
              <h3><strong> {{job}} </strong></h3>
              <div class='job-section'>
              <p><strong>Company: </strong>{{job.company_name}}</p>
              </div>
              <div class='job-section'>
              <p><strong>Job Type: </strong>{{job.job_type}}</p>
              </div>
	      <div class='job-section'>
                <p><strong>About {{job.company_name}} </strong></p>
                <p class='job-content'>{{job.about_company}}</p>
              </div>
              <div class='job-section'>
              <p><strong>Description </strong></p>
              <p class='job-content'>{{job.description}}</p>
              </div>
              <div class='job-section'>
              <p><strong>Qualification </strong></p>
              <p class='job-content' >{{job.qualification}}</p>
              </div>
              <div class='job-section'>
              {% if job.more_info %}
              <p><strong>More</strong></p>
              <p class='job-content'>{{job.more_info}}</p>
              {% endif %}
              </div>
              {% if job.link %}
              <div class='job-section'>
              <p class='job-content'><a href='{{job.link}}'> Go to Job </a></p>
              </div>
              {% endif %}


            </div>
          </div>
        </div>
    </div>


<div class='col-md-3 ads-container'>

  <div class='row'>

    <h5 class='text-center'> Ads </h5>
    <div class='well asd_arnd_u'>
    </div>
  </div>
</div>




{% endblock %}