Dzcover/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from user_app import views as user
# from search_app import views as search
from django.contrib.auth import views as auth_views



urlpatterns = [
    url(r'^$', user.Login.as_view(), name= 'index'),
    url(r'^signup/$', user.signup, name='signup'),
    url(r'^signup/confirm$', user.signup_confirm_message, name='signup_confirm_message'),
    url(r'^admin/', admin.site.urls),
    url(r'^register/username/$', user.check_username, name='check_username'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        user.ActivateLinkView.as_view(), name='activate'),
    url(r'^resend/activation/$', user.resend_activate_link, name='resend_activation'),
    url(r'^logout/$', user.user_log_out, name='logout'),
    url(r'^view/(?P<username>\w+)/$', user.view_user, name='view_user'),
    url(r'^view/(?P<username>\w+)/network/$', user.view_network, name='view_network'),
    url(r'^view/(?P<username>\w+)/recommendation/$', user.RecommendedView.as_view(), name='view_recommended'),
    url(r'^network/delete/(?P<username>\w+)/$', user.remove_network, name='remove_network'),
    url(r'^job/', include('job_app.urls', namespace='job')),
    url(r'^people/$', user.DiscoverPeople.as_view(), name='discover_people'),
    url(r'^notifications/$', user.NotificationView.as_view(), name='notifications'),
    url(r'^quicksearch/$', user.quick_search, name='quick_search'),
    url(r'^poll/updates/$' ,user.poll_updates, name='poll_updates'),
    url(r'^request/accept/(?P<username>\w+)/$' ,user.accept_request, name='accept_request'),
    url(r'^request/decline/(?P<username>\w+)/$' ,user.decline_request, name= 'decline_request'),
    url(r'^request/send/(?P<username>\w+)/$' ,user.send_request, name='send_request'),
    url(r'^recommend/(?P<username>\w+)/$' ,user.recommend_user, name='recommend_action'),
    url(r'^request/remove/(?P<username>\w+)/$' ,user.remove_request, name='delete_request'),
    url(r'^edit/profile/$', user.EditProfile.as_view(), name='profile_edit'),
    url(r'^view/(?P<username>\w+)/album/', include('album_app.urls', namespace='album')),
    url(r'^view/(?P<username>\w+)/notes/', include('notes_app.urls', namespace='notes')),
    url(r'^view/(?P<username>\w+)/about-me/', user.about_me, name='about_me'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^about/$', user.help, name='help'),
    url(r'^privacy/$', user.privacy, name='privacy'),
    url(r'^cookies/$', user.cookies, name='cookies'),
    url(r'^view/(?P<username>\w+)/account/$', user.view_account, name='view_account'),
    url(r'^(?P<username>\w+)/account/delete/$', user.delete_account, name='delete_account'),
    url(r'^terms-and-conditions/$', user.terms_and_condition, name='terms')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job_app/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    url(r'^feed/$', views.job_feed, name= 'feed'),
    url(r'^guide/$', views.job_post_guide, name= 'guide'),
    url(r'^posted/(?P<username>\w+)$', views.view_posted_jobs, name= 'posted'),
    url(r'^create/$', views.CreateJob.as_view(), name= 'create'),
    url(r'^delete/$', views.delete_posted_job, name='delete_job'),
    url(r'^edit/(?P<job_id>\w+)/$', views.JobEdit.as_view(), name= 'edit'),
    url(r'^view/(?P<slug>[-\w\d]+),(?P<job_id>\w+)$', views.view_job, name= 'view_job'),
    url(r'^search/$', views.JobList.as_view(), name='discover_jobs'),
]

templates/note/notes.html
{% extends 'users/portfolio_base.html'%}
{% load static from staticfiles%}
{% block body_tag%} class='notes' {% endblock%}
{% block portfolio-body %}


<div class='col-xs-12 col-md-9'>
  <p class='portfolio-header'> Notes </p>
  <h5><strong>Write Once. Share Everywhere.</strong> </h5>
  <br>
  <div>

  {% ifequal view_user request.user %}
  <a href='{% url "notes:create" username=request.user.username %}'>Create a Note </a>
{% endifequal %}
      <div class='row note-column'>
        <!-- <p>Notes: <span id='total_notes'> {{total}} </sapn></p> -->
      {% if notes%}

      <ul class='list-unstyled list-inline'>
          {% for note in notes %}
          <li class='note-card col-xs-12' data-id='{{note.id}}' data-url='{{note.get_full_absolute_url}}'>
              <a href='{{note.get_absolute_url}}' class='note-header'><strong>{{note.title}}</strong></a>
              <p class='note-content'>{{note.content|truncatechars:200}}</p>

            <ul class='list-unstyled list-inline note-meta note-footer'>
                <li> {{note.created_on|date}}</li>
                <li> {{note.count_views}}</li>
              </ul>
              <br>
              <ul class='list-unstyled list-inline note-meta note-footer'>
                <div class='dropdown' style='display:inline-block'>
                  <a class='btn btn-sm btn-default note-tool' data-toggle='dropdown' > Share</a>
                  <div class='dropdown-menu'>
                   <li><a href="https://twitter.com/home?status=Check%20out%20{{note.user.first_name}}%20notes%20on%20dzcover%20{{note.get_full_absolute_url}}" target='_blank'>Share note on Twitter</a></li>
                   <li><a href="https://www.facebook.com/sharer/sharer.php?u={{note.get_full_absolute_url}}" target='_blank'>Share note on Facebook</a></li>
                   <li><a class='copy-note-link'>Copy link</a></li>
                  </div>
                </div>
                {% ifequal request.user note.user %}
                <li class='note-tool'><a href='{% url "notes:edit" username=note.user.username pk=note.id%}' class='btn btn-sm btn-default'>
                    Edit
                </a>
                </li>
                <li class='note-tool'><a class='delete-note btn btn-sm btn-default' > Delete</a></li>
                {% endifequal %}
              </ul>
          </li>
          {% endfor %}
              {% if notes.paginator.num_pages > 1 %}
              <ul class="pagination center-block text-center">

              <span class="step-links custom-step-links">

                {% if notes.has_previous %}
                <a class='btn-sm btn page-previous' href="?page={{ notes.previous_page_number }}"><i class="icon ion-ios-arrow-thin-left"></i> <strong>Prev </steong></a>
                {% endif %}


                {% if notes.has_next %}
                <a class='btn-sm btn page-next' href="?page={{ notes.next_page_number }}"><strong>Next </steong><i class="icon ion-ios-arrow-thin-right"></i></a>
                {% endif %}

              </span>
             </ul>
             {% endif %}
    </ul>
    {% else %}
      <!-- <br>
      <p class='text-center'>No Notes <i class='icon ion-ios-book-outline'></i> </p> -->
    {% endif %}



    </div>

    <div class='modal' id ='link-modal'>
      <div class='modal-dialog'>
        <div class='modal-content'>
          <div class='modal-header'>
          </div>
          <div classs='modal-body'>
            <a id='note-link'> hey</a>
          </div>
          <div class='modal-footer'>
          </div>
        </div>
      </div>
    </div>

</div>
</div>
<div class='col-md-3 ads-container'>
  {% include 'ads.html'%}
</div>


{% endblock %}

templates/note/read_note.html
{% extends 'users/container.html'%}
{% load static from staticfiles%}
{% block mainarticle %}

<div class='col-xs-12 col-md-9'>
  <br>
  <div class=' col-md-12 text-justify'>
      <a href='{{note.get_full_absolute_url}}' class='note-header'><strong>{{note.title}}</strong></a>
      <p class='note-content'>{{note.content}}</p>
	<br>
	 <div class='dropdown' style='display:inline-block'>
          <a class='btn btn-sm btn-default' data-toggle='dropdown' > Share</a>
            <div class='dropdown-menu'>
              <li><a href="https://twitter.com/home?status=Check%20out%20{{note.user.first_name}}%20notes%20on%20dzcover%20{{note.get_full_absolute_url}}" target='_blank'>Share note on Twitter</a></li>
              <li><a href="https://www.facebook.com/sharer/sharer.php?u={{note.get_full_absolute_url}}" target='_blank'>Share note on Facebook</a></li>
              <li><a data-toggle='modal' data-target='#copy-link-modal'>Copy link</a></li>
             </div>
           </div>
      <div>
	
	<br>

      <img src='{{note.user.get_avatar}}' class='avatar-sm'>
      <p>by <a href='{{note.user.get_absolute_url}}'>{{note.user.get_full_name}}</a></p>
     </div>


      <ul class='list-unstyled list-inline'>
        <li>{{note.created_on|date}}</li>
        <li> {{note.count_views}}</li>
      </ul>



  </div>
</div>




<div class='modal' id ='copy-link-modal'>

<div class='modal-dialog'>
 <div class='modal-content'>
   <div class='modal-header'>
   </div>
   <div classs='modal-body'>
   Link:   <a>{{note.get_full_absolute_url}} </a>
   </div>
   <div class='modal-footer'>
   </div>
 </div>
</div>
</div>


<div class='col-md-3 ads-container'>

    {% include 'ads.html'%}

</div>

<br>


{% endblock %}

templates/note/update_note.html
{% extends 'users/container.html'%}
{% load static from staticfiles%}

{% block mainarticle %}
<div class='col-xs-12 col-md-9'>
  <h3>Your Note</h3>
  <br>
<div id='new_note'>
  <form action='' method="POST" class='note-form'>
    {% csrf_token%}
    <div>
      <div class='fieldWrapper'>
        {{ form.title.errors }}
        {{ form.title.label_tag }}
        {{ form.title }}
      </div>
    </div>
      <div class='fieldWrapper'>
        {{ form.content.errors }}
          <label class ='sr-only' for= 'content'> Content </label>
        {{ form.content }}
      </div>
    <button type='submit' class='btn btn-sm btn-default'>Save</button>
  </form>

</div>
</div>

<div class='col-md-3 ads-container'>
    {% include 'ads.html' %}
</div>

{% endblock %}
