Dzcover/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from user_app import views as user
# from search_app import views as search
from django.contrib.auth import views as auth_views



urlpatterns = [
    url(r'^$', user.Login.as_view(), name= 'index'),
    url(r'^signup/$', user.signup, name='signup'),
    url(r'^signup/confirm$', user.signup_confirm_message, name='signup_confirm_message'),
    url(r'^admin/', admin.site.urls),
    url(r'^register/username/$', user.check_username, name='check_username'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        user.ActivateLinkView.as_view(), name='activate'),
    url(r'^resend/activation/$', user.resend_activate_link, name='resend_activation'),
    url(r'^logout/$', user.user_log_out, name='logout'),
    url(r'^view/(?P<username>\w+)/$', user.view_user, name='view_user'),
    url(r'^view/(?P<username>\w+)/network/$', user.view_network, name='view_network'),
    url(r'^view/(?P<username>\w+)/recommendation/$', user.RecommendedView.as_view(), name='view_recommended'),
    url(r'^network/delete/(?P<username>\w+)/$', user.remove_network, name='remove_network'),
    url(r'^job/', include('job_app.urls', namespace='job')),
    url(r'^people/$', user.DiscoverPeople.as_view(), name='discover_people'),
    url(r'^notifications/$', user.NotificationView.as_view(), name='notifications'),
    url(r'^quicksearch/$', user.quick_search, name='quick_search'),
    url(r'^poll/updates/$' ,user.poll_updates, name='poll_updates'),
    url(r'^request/accept/(?P<username>\w+)/$' ,user.accept_request, name='accept_request'),
    url(r'^request/decline/(?P<username>\w+)/$' ,user.decline_request, name= 'decline_request'),
    url(r'^request/send/(?P<username>\w+)/$' ,user.send_request, name='send_request'),
    url(r'^recommend/(?P<username>\w+)/$' ,user.recommend_user, name='recommend_action'),
    url(r'^request/remove/(?P<username>\w+)/$' ,user.remove_request, name='delete_request'),
    url(r'^edit/profile/$', user.EditProfile.as_view(), name='profile_edit'),
    url(r'^view/(?P<username>\w+)/album/', include('album_app.urls', namespace='album')),
    url(r'^view/(?P<username>\w+)/notes/', include('notes_app.urls', namespace='notes')),
    url(r'^view/(?P<username>\w+)/about-me/', user.about_me, name='about_me'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^about/$', user.help, name='help'),
    url(r'^privacy/$', user.privacy, name='privacy'),
    url(r'^cookies/$', user.cookies, name='cookies'),
    url(r'^view/(?P<username>\w+)/account/$', user.view_account, name='view_account'),
    url(r'^(?P<username>\w+)/account/delete/$', user.delete_account, name='delete_account'),
    url(r'^terms-and-conditions/$', user.terms_and_condition, name='terms')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job_app/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    url(r'^feed/$', views.job_feed, name= 'feed'),
    url(r'^guide/$', views.job_post_guide, name= 'guide'),
    url(r'^posted/(?P<username>\w+)$', views.view_posted_jobs, name= 'posted'),
    url(r'^create/$', views.CreateJob.as_view(), name= 'create'),
    url(r'^delete/$', views.delete_posted_job, name='delete_job'),
    url(r'^edit/(?P<job_id>\w+)/$', views.JobEdit.as_view(), name= 'edit'),
    url(r'^view/(?P<slug>[-\w\d]+),(?P<job_id>\w+)$', views.view_job, name= 'view_job'),
    url(r'^search/$', views.JobList.as_view(), name='discover_jobs'),
]

templates/ads.html
<div>
  <h4> Ads </h4>
</div>

templates/base.html
<!doctype html>

<html>

<head>
    <title>Dzcover</title>
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable =no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <meta property="og:description" content="Express Yourself. Make your official account. Find Jobs . Find Networks. We have created a space for you">
    <meta name="description" content="Express Yourself. Make your official account. Find Jobs . Find Networks. We have created a space for you">
    <meta name="twitter:description" content="Express Yourself. Make your official account. Find Jobs . Find Networks. We have created a space for you">
    <meta name="twitter:title" content="Dzcover">
    <meta property="og:site_name" content="Dzcover">
    <meta property="og:title" content="Dzcover">
    <meta name="google-site-verification" content="D8c3Fq0ITXJ9VyyaJser8qdwcKuUTUORsUZT2v4dbEM" />
    {% load static from staticfiles %}
    <link href= "{% static 'css/bootstrap.min.css' %}" rel='stylesheet' type='text/css'>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans|Quicksand" rel="stylesheet">
     <link href="https://fonts.googleapis.com/css?family=Zilla+Slab" rel="stylesheet"> 
    <link href= "{% static 'css/cropper.min.css' %}" rel='stylesheet' type='text/css'>
     <link rel="stylesheet" href="{% static 'css/teleport-autocomplete.min.css'%}">
     <link rel= "stylesheet" href = "{% static 'css/style.css' %}" type= 'text/css'>
    <link rel="shortcut icon" href="{% static 'images/logo/favicon.png'%}" type="image/x-icon">
    <!--[if lt IE 9]>
  <script src="{% static 'js/respond.min.js' %}"></script>
<![endif]-->
    {% block css%}
    {%endblock%}
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-3257542564757536",
    enable_page_level_ads: true
  });
</script>

</head>

<body {% block body_tag%} {% endblock%}>

 <div class='container'>
    <header>
        {% block header %}{% endblock %}
        <nav>

                {% block navigation%}{% endblock %}

        </nav>
    </header>

    <content>
      <div class='row content'>
        {% block mainarticle %}{% endblock %}
      </div>
    </content>

    <aside>
        {% block aside %}{% endblock %}
    </aside>

    <footer>
      <div class='row' id='footer'>
        <ul class='list-unstyled list-inline text-center'>
            <li><a href='{% url "job:guide" %}' class='footer-links'>Post Jobs</a></li>
            <li><a href='{% url "cookies" %}' class='footer-links'>Cookies</a></li>
            <li><a href='{% url "terms" %}' class='footer-links'>Terms</a></li>
            <li><a href='{% url "privacy" %}' class='footer-links'>Privacy</a></li>
            <li><a href='{% url "help" %}' class='footer-links'>Help</a></li>
          <p id='copyright'>&copy; Dzcover 2017</p>
        </ul>
      </div>
    </footer>
 </div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
 <script src= "{% static 'js/bootstrap.min.js' %}" ></script>
 <script src= "{% static 'js/script.js' %}" ></script>
 <script src= "{% static 'js/cropper.min.js' %}" ></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
<script src="{% static 'js/teleport-autocomplete.min.js' %}" ></script>
<script src= "{% static 'js/ga.js' %}" ></script>

 {% block javascript %}
 {% endblock %}


</body>
</html>