Dzcover/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from user_app import views as user
# from search_app import views as search
from django.contrib.auth import views as auth_views



urlpatterns = [
    url(r'^$', user.Login.as_view(), name= 'index'),
    url(r'^signup/$', user.signup, name='signup'),
    url(r'^signup/confirm$', user.signup_confirm_message, name='signup_confirm_message'),
    url(r'^admin/', admin.site.urls),
    url(r'^register/username/$', user.check_username, name='check_username'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        user.ActivateLinkView.as_view(), name='activate'),
    url(r'^resend/activation/$', user.resend_activate_link, name='resend_activation'),
    url(r'^logout/$', user.user_log_out, name='logout'),
    url(r'^view/(?P<username>\w+)/$', user.view_user, name='view_user'),
    url(r'^view/(?P<username>\w+)/network/$', user.view_network, name='view_network'),
    url(r'^view/(?P<username>\w+)/recommendation/$', user.RecommendedView.as_view(), name='view_recommended'),
    url(r'^network/delete/(?P<username>\w+)/$', user.remove_network, name='remove_network'),
    url(r'^job/', include('job_app.urls', namespace='job')),
    url(r'^people/$', user.DiscoverPeople.as_view(), name='discover_people'),
    url(r'^notifications/$', user.NotificationView.as_view(), name='notifications'),
    url(r'^quicksearch/$', user.quick_search, name='quick_search'),
    url(r'^poll/updates/$' ,user.poll_updates, name='poll_updates'),
    url(r'^request/accept/(?P<username>\w+)/$' ,user.accept_request, name='accept_request'),
    url(r'^request/decline/(?P<username>\w+)/$' ,user.decline_request, name= 'decline_request'),
    url(r'^request/send/(?P<username>\w+)/$' ,user.send_request, name='send_request'),
    url(r'^recommend/(?P<username>\w+)/$' ,user.recommend_user, name='recommend_action'),
    url(r'^request/remove/(?P<username>\w+)/$' ,user.remove_request, name='delete_request'),
    url(r'^edit/profile/$', user.EditProfile.as_view(), name='profile_edit'),
    url(r'^view/(?P<username>\w+)/album/', include('album_app.urls', namespace='album')),
    url(r'^view/(?P<username>\w+)/notes/', include('notes_app.urls', namespace='notes')),
    url(r'^view/(?P<username>\w+)/about-me/', user.about_me, name='about_me'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^about/$', user.help, name='help'),
    url(r'^privacy/$', user.privacy, name='privacy'),
    url(r'^cookies/$', user.cookies, name='cookies'),
    url(r'^view/(?P<username>\w+)/account/$', user.view_account, name='view_account'),
    url(r'^(?P<username>\w+)/account/delete/$', user.delete_account, name='delete_account'),
    url(r'^terms-and-conditions/$', user.terms_and_condition, name='terms')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

album_app/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    url(r'^$', views.ViewAlbum.as_view(), name= 'view_album'),
    url(r'^delete/$', views.delete_photo, name='delete_photo'),
]

job_app/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    url(r'^feed/$', views.job_feed, name= 'feed'),
    url(r'^guide/$', views.job_post_guide, name= 'guide'),
    url(r'^posted/(?P<username>\w+)$', views.view_posted_jobs, name= 'posted'),
    url(r'^create/$', views.CreateJob.as_view(), name= 'create'),
    url(r'^delete/$', views.delete_posted_job, name='delete_job'),
    url(r'^edit/(?P<job_id>\w+)/$', views.JobEdit.as_view(), name= 'edit'),
    url(r'^view/(?P<slug>[-\w\d]+),(?P<job_id>\w+)$', views.view_job, name= 'view_job'),
    url(r'^search/$', views.JobList.as_view(), name='discover_jobs'),
]

notes_app/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    url(r'^$', views.ViewNotes.as_view(), name= 'view_notes'),
    url(r'^create$', views.CreateNote.as_view(), name= 'create'),
    url(r'^read/(?P<slug>[-\w\d]+),(?P<id>\w+)$', views.read_note, name= 'read_note'),
    url(r'^edit/(?P<pk>\w+)$', views.EditNote.as_view(), name= 'edit'),
    url(r'^delete/$', views.delete_note, name='delete_note'),
]

templates/users/about_me.html
{% extends 'users/portfolio_base.html'%}
{% load static from staticfiles%}

{% block portfolio-body %}

<div class='row'>
  <div class='col-xs-12 col-md-9'>
    <div class='text-center profile-head'>
      <div class='row'>
      <img class='avatar-md img-round-container' src='{{view_user.get_avatar}}'/>
      </div>
        <h4><strong>{{view_user.get_full_name}}</strong></h4>
        <p>{{view_user.get_location}}</p>
        <ul class='list-inline list-unstyled profile-info'>
            <li class='profile-tool'><a href='{% url "view_network" username=view_user.username%}'>

              <span class='center-block {% ifequal request.user view_user %}network-count{% endifequal %}'><strong>{{view_user.count_network}}</strong> </span>
              <span></strong>Connects</strong> </span>
            </a></li>
            <li class='profile-tool'><a href = '{% url "view_recommended" username=view_user.username%}' >

              <span class='center-block {% ifequal request.user view_user %}recommendation-count{% endifequal %}'><strong>{{view_user.count_recommended}}</strong></span>
              <span></strong>Recommends</strong> </span>

	</a></li>
        </ul>
  </div>


    <div class='col-xs-12'>
      <div class='about-me-section'>
          <h5><strong> What i do</strong></h5>
        <p>{{view_user.profession}}</p>
      </div>

    <div class='about-me-section'>
      <h5><strong> Currently </strong></h5>
      <p> {{view_user.get_current_job}}</p>
    </div>

    <div class='about-me-section'>
      <h5><strong>About Me</strong></h5>
      {{ view_user.get_about_me|urlize}}
</div>
</div>
</div>

<div class='col-xs-12 col-md-3'>
  <div class='ads-container'>
    {% include 'ads.html' %}
  </div>
  <div class='recommended-container'>
    <h5>{% ifequal view_user request.user %}You {% else %}{{view_user.first_name|title}} {%endifequal%}Recommended</h5>
      {% if recommendation %}
      <ul class='list-unstyled'>
      {% for person in recommendation %}
        <li>
          <div class='profile-sm-card'>

              <img class='avatar-sm pull-left' src='{{person.get_avatar}}'
              />

            <div class='person-header'>
                <a href='{{person.get_absolute_url}}'> <strong> {{person.get_full_name}}</strong></a>
            </div>
          </div>
        </li>
        {% endfor %}
      </ul>
        {% else%}
        {% ifequal view_user request.user %}
      <div >
        <p class='text-justify'> Hi {{ view_user.first_name }}, you can recommend up to 20 people on your page.</p>
        <a href='{%url "view_network" username=view_user.username%}'>recommend from your connections?</a>
        {% else %}
        <p > No recommended user.</p>
      </div>

        {% endifequal %}
        {% endif %}


</div>
</div>
</div>




{% endblock %}


templates/users/account.html
{% extends 'users/portfolio_base.html'%}
{% load static from staticfiles%}

{% block portfolio-body %}
<div class='col-xs-12 col-md-9'>
  <div class='row'>
    <h4> Account Details </h4>
    <p><strong> User : {{view_user.get_full_name}} </strong></p>
    <p><strong> Email : {{view_user.email}} </strong></p>
    <p><strong> Date Joined : {{view_user.date_joined|date}} </strong></p>
    <p><strong> Active : {{view_user.is_active}} </strong></p>
    <p><strong> Job Poster : {{job_poster}} </strong></p>
    <p> <a href='{% url "delete_account" username=view_user.username %}'> Delete Account </a> please note deletion of account takes up to a week to process. Your account will be inactive during this process. </p>
    <p> People will still be able to access your profile during this time. </p>
    <P> To reactivate your account during this 7 day period send an email to <a>support@dzcover.com</a>. </p>
    <p> If there is a need for <strong> Immediate </strong> deletion of account please send a request with your dzcover email to <a>support@dzcover.com</a> </p>

  </div>
</div>
{% endblock %}

templates/users/container.html
{% extends 'base.html' %}
{% load static from staticfiles%}

{% block css%}
<link href= "{% static 'css/container.css' %}" rel='stylesheet' type='text/css'>
{% block add-css%}
{% endblock%}
{% endblock%}

{% block navigation%}
<nav class="navbar navbar-default navbar-fixed-top nav-container nav-dzcover">
  <div class="container">
    <div class='navbar-header center-block text-center'>
      <ul class="nav navbar-nav " >
        <li><a href="{% url 'index' %}">
          <div class="svg-icon">
            <svg  xmlns="http://www.w3.org/2000/svg" width="512px" height="512px"  class='ion ion-18' viewBox="0 0 512 512"  id='ion-person' aria-labelledby="title-you desc-you">
              <title id='title-you'> You </title>
              <desc id='desc-you'> Your Page </desc>
              <g>
            <path d="M448 448s0-26.4-2.2-40.2c-1.8-10.9-16.9-25.3-81.1-48.9-63.2-23.2-59.3-11.9-59.3-54.6 0-27.7 14.1-11.6 23.1-64.2 3.5-20.7 6.3-6.9 13.9-40.1 4-17.4-2.7-18.7-1.9-27 .8-8.3 1.6-15.7 3.1-32.7 1.8-21-17.7-76.3-87.6-76.3-69.9 0-89.4 55.3-87.5 76.4 1.5 16.9 2.3 24.4 3.1 32.7.8 8.3-5.9 9.6-1.9 27 7.6 33.1 10.4 19.3 13.9 40.1 9 52.6 23.1 36.5 23.1 64.2 0 42.8 3.9 31.5-59.3 54.6-64.2 23.5-79.4 38-81.1 48.9C64 421.6 64 448 64 448h384z"></path>
             </g>
          </svg>
        </div>
        <span>You</span></a>
      </li>

      <li><a href="{% url 'job:discover_jobs' %}" >
        <div class="svg-icon ">
          <svg  xmlns="http://www.w3.org/2000/svg" width="512px" height="512px"  class='ion ion-18' viewBox="0 0 512 512"  id='ion-briefcase' aria-labelledby="title-jobs desc-jobs">
            <title id='title-jobs'> Jobs </title>
            <desc id='desc-jobs'> Search for Jobs </desc>
          <g>
          <path d="M272 272h-32v-8H32v176c0 4.4 3.3 8 7.8 8h432.5c4.4 0 7.7-3.6 7.7-8V264H272v8zM472.2 144H352v-30.7C351 85.1 330.3 64 300.8 64h-89.6c-29.4 0-50.2 21.1-51.2 49.3V144H39.8c-4.4 0-7.8 3.6-7.8 8v96h208v-8h32v8h208v-96c0-4.4-3.3-8-7.8-8zM320 116.2V144H192v-26.8-1-1c0-9.7 8.6-19.2 18.8-19.2h90.4c10.1 0 18.8 9.4 18.8 19.2v1z"></path>
          </g>
        </svg>
      </div>
      <span>Jobs</span>
      </a>
      </li>

      <li><a href="{% url 'discover_people' %}">
            <div class="svg-icon">
            <svg  xmlns="http://www.w3.org/2000/svg" width="512px" height="512px"  class='ion ion-18' viewBox="0 0 512 512"  id='ion-people-b' aria-labelledby="title-people desc-people">
                <title id='title-people'> People </title>
                <desc id='desc-people'> Search for People </desc>
                <g>
              <path d="M425.3 324.8c-41.4-15.7-38.9-9.4-38.9-38.5 0-18.8 9.3-11.9 15.2-47.7 2.3-14.1 4.2-4.7 9.1-27.3 2.6-11.8-1.8-12.7-1.2-18.3.5-5.6 1-10.7 2-22.2 1.2-14.4-11.6-52-57.4-52s-58.6 37.6-57.4 52c.9 11.6 1.5 16.6 2 22.2.5 5.6-3.8 6.5-1.2 18.3 4.9 22.6 6.8 13.1 9.1 27.3 5.9 35.8 15.1 29 15.1 47.7 0 13.4 3.1 19-14.9 27.5 5.4 1.9 11.7 4.2 19.3 7.1 54.4 20.7 53.1 40.8 54.5 50.3 1 6.5 1.5 58.3 1.7 76.8H480s0-80.5-1.5-89.9c-1.1-7.4-11-17.2-53.2-33.3z"></path><path d="M357 448s0-14.1-.2-30.4c-.2-18.6-.7-40-1.7-46.4-1.5-9.5-14.3-22.2-68.6-42.9-7.5-2.8-13.8-5.1-19.3-7.1-33.3-11.8-30.9-15.7-30.9-48 0-24.3 12-8.5 19.6-54.6 3-18.2 5.4-6.1 11.7-35.2 3.4-15.2-2.3-16.4-1.6-23.7.7-7.3 1.4-13.8 2.6-28.7 1.6-18.5-14.9-67.1-74.1-67.1-59.2 0-75.6 48.5-74.1 67.1 1.2 14.9 1.9 21.4 2.7 28.7.7 7.3-5 8.4-1.6 23.7 6.4 29.1 8.8 17 11.8 35.2 7.6 46.1 19.5 30.3 19.5 54.6 0 37.6 3.3 34.8-50.2 55.1C48.3 349 35.5 361.7 34 371.2c-2 12.1-2 76.8-2 76.8h325z"></path>
                </g>
             </svg>
           </div>
          <span> People</span>
         </a>
      </li>

      </ul>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class='nav navbar-right'>
          <form class="text-center navbar-form quicksearch-form" autocomplete="off">
              {{quicksearchform}}
          </form>
          <div class='quicksearch-result-container'>
              <div id='quicksearch-result'>
              </div>
          </div>
      </ul>
    </div>
  </div>
</nav>

{% endblock %}

{% block mainarticle %}

{% endblock %}

{% block aside %}
<div class='notification-box'>
  {% csrf_token %}
  <div id='notification-view' class='collapse'>

  </div>
  <h6 class='text-center'><a id='notification-toggle' data-toggle='collapse' href='#notification-view'>
    NOTIFICATIONS </a> <span id='notification-count'> {{notification_count|default:""}} </span></h6>
</div>
{% endblock %}

templates/users/discover_people.html
{% extends 'users/container.html'%}
{% load static from staticfiles%}

{% block mainarticle %}
<h3 class='text-center discover-title'> Discover People</h3>
  <div class='col-md-3'>
    <div class='text-center'>
    <p> Hey {{request.user.first_name}}, invite your Friends </p>
    <ul class='list-unstyled list-inline'>
    <li><a href="https://twitter.com/home?status=Hey,%20join%20Dzcover%20{{SITE_URL}}" target='_blank'>
      <svg  xmlns="http://www.w3.org/2000/svg" width="512px" height="512px"  class='ion ion-26' viewBox="0 0 512 512"  id='ion-ios-twitter-outline' aria-labelledby="title-twitter">
        <title id='title-facebook'> Share on Twitter</title>
      <g>
      <path d="M492 109.5c-17.4 7.7-36 12.9-55.6 15.3 20-12 35.4-31 42.6-53.6-18.7 11.1-39.4 19.2-61.5 23.5-17.7-18.9-43-30.7-70.7-30.7-53.5 0-96.8 43.4-96.8 96.9 0 7.6.8 15 2.5 22.1-80.5-4-152-42.6-199.7-101.3-8.3 14.3-13.1 31-13.1 48.7 0 33.6 17.1 63.3 43.1 80.7C67 210.7 52 206.3 39 199v1.2c0 47 33.4 86.1 77.7 95-8.1 2.2-16.7 3.4-25.5 3.4-6.2 0-12.3-.6-18.2-1.8 12.3 38.5 48.1 66.5 90.5 67.3-33.1 26-74.9 41.5-120.3 41.5-7.8 0-15.5-.5-23.1-1.4C62.8 432 113.7 448 168.3 448 346.5 448 444 300.3 444 172.2c0-4.2-.1-8.4-.3-12.5C462.5 146 479 129 492 109.5zm-57.8 37.2l-7 5.1.4 8.6c.2 3.8.3 7.8.3 11.8 0 30.2-5.9 61.8-17 91.5-11.7 31.2-28.5 59.4-50 83.8-23 26.1-50.2 46.5-81.1 60.8-33.8 15.7-71.3 23.6-111.5 23.6-28.9 0-57.4-4.8-84.5-14.2 9.9-1.9 19.6-4.6 29.1-7.9 21.7-7.6 41.9-18.7 60.1-33l35.3-27.7-44.9-.8c-26.1-.5-49.7-13.4-64.3-33.9 7.3-.5 14.5-1.8 21.5-3.7l60.7-20.2-61.7-10.9c-29.6-5.9-52.8-27.9-61.3-55.8 7.8 2 15.4 2.8 23.9 3.3 0 0 31.8 1.4 55.8-.1-13-6.2-46.4-29.2-46.4-29.2-22.5-15.1-36-40.2-36-67.4 0-6.4.8-12.8 2.2-19 21.9 22.4 47 41.1 75.1 55.5 37 19.1 76.9 29.8 118.6 31.9l21.2 1.1-4.8-20.7c-1.4-5.9-2.1-12.1-2.1-18.5 0-44.4 36.3-80.7 80.9-80.7 22.3 0 43.8 9.3 59 25.6l6.1 6.5 8.7-1.7c4.5-.9 8.9-1.9 13.3-3.1-1 1.4-5.7 6.1-11 10.8-4.5 4-17.8 16.5-17.8 16.5s13 4.1 21.1 5c8.1.9 17.4-.6 18.9-.8-2.8 2.3-7.8 5.8-10.8 7.9z">
      </g>
      </svg>
      </path>
    </a></li>
    <li><a href="https://www.facebook.com/sharer/sharer.php?u={{SITE_URL}}" target='_blank'>
      <svg  xmlns="http://www.w3.org/2000/svg" width="512px" height="512px"  class='ion ion-26' viewBox="0 0 512 512"  id='ion-ios-facebook-outline' aria-labelledby="title-facebook">
        <title id='title-facebook'> Share on Facebook</title>
      <g>
        <path d="M288 192v-38.1c0-17.2 3.8-25.9 30.5-25.9H352V64h-55.9c-68.5 0-91.1 31.4-91.1 85.3V192h-45v64h45v192h83V256h56.4l7.6-64h-64zm42.2 48H272v192h-51V240h-45v-32h45v-58.7c0-24.5 5.4-41.2 15.5-51.8 11.2-12 31.1-17.5 59.6-17.5H336v32h-17.5c-12 0-27.5 1.1-37.1 11.7-8.1 9-9.4 20.1-9.4 30.1V208h62l-3.8 32z"></path>
      </g>
      </svg>
    </a></li>
  </ul>
</div>
  </div>
<div class='col-xs-12 col-sm-6'>
{% include 'users/list_people.html' %}
</div>

  <div class='col-md-3 ads-container'>
      {% include 'ads.html' %}
  </div>
  {%endblock%}

templates/users/list_people.html
<div class='row'>
  <div class='col-sm-6 col-sm-offset-3 '>
  <form action ='' method = 'GET' class='discover-people-form'>
    <div class='form-group form-inline text-center'>
      <div class="input-group">
      {{form}}
       <div class="input-group-btn">
        <button class='btn btn-default form-control'>
          <svg  xmlns="http://www.w3.org/2000/svg" width="512px" height="512px"  class='ion ion-18' viewBox="0 0 512 512"  id='ion-search'>
              <g>
          <path d="M445 386.7l-84.8-85.9c13.8-24.1 21-50.9 21-77.9C381.2 135.3 310 64 222.6 64 135.2 64 64 135.3 64 222.9c0 87.6 71.2 158.9 158.6 158.9 27.9 0 55.5-7.7 80.1-22.4l84.4 85.6c1.9 1.9 4.6 3.1 7.3 3.1s5.4-1.1 7.3-3.1l43.3-43.8c4-4.1 4-10.5 0-14.5zM222.6 125.9c53.4 0 96.8 43.5 96.8 97s-43.4 97-96.8 97-96.8-43.5-96.8-97 43.4-97 96.8-97z"></path>
        </g>
        </svg>
        </button>
      </div>
    </div>
    </div>
  </form>
</div>
</div>
  <div class='people-container'>
      <div class='row'>
        {% if people%}

        <ul class='list-unstyled '>

          {% for person in people %}

           <li class='person-card col-sm-6' data-username= '{{ person.username }}'>
               <div class='text-center'>
                   <img class='avatar-md' src='{{person.get_avatar}}'/>
                 <h4><a href='{{person.get_absolute_url}}' class='text-center'> <strong>  {{person.get_full_name|truncatechars:35}}</strong> </a></h4>
                 <p class='person-info'>{{person.get_profession|truncatechars:35}}</p>
               </div>
           </li>
          {% endfor %}
          <ul class="pagination center-block text-center">
              {% if people.paginator.num_pages > 1 %}
              <span class="step-links custom-step-links">

                {% if people.has_previous %}
                <a class='btn-sm btn page-previous' href="?search_people={{request.GET.search_people}}&amp;page={{ people.previous_page_number }}"><i class="icon ion-ios-arrow-thin-left"></i> <strong>Prev </steong></a>
                {% endif %}

                {% if people.has_next %}
                <a class='btn-sm btn page-next' href="?search_people={{request.GET.search_people}}&amp;page={{ people.next_page_number }}"><strong>Next </steong><i class="icon ion-ios-arrow-thin-right"></i></a>
                {% endif %}

              </span>
              {% endif %}
            </ul>
        </ul>
          {% else%}
          {% if request.GET.search_people %}
          <p class='text-center'> we could not find <i>{{ request.GET.search_people}} </i> </p>
          {% endif %}
          {% endif %}
      </div>
    </div>

templates/users/portfolio_base.html
{% extends 'users/container.html'%}
{% load static from staticfiles%}

{% block add-css%}
<link href= "{% static 'css/portfolio.base.css' %}" rel='stylesheet' type='text/css'>
{%endblock%}

{% block mainarticle %}
<div>
  <nav class="navbar">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target="#nav-portfolio-container">

              <svg  xmlns="http://www.w3.org/2000/svg" width="512px" height="512px"  class='ion ion-24' viewBox="0 0 512 512"  id='ion-grid' aria-labelledby="title-menu title-desc" role="menu">
                <title id='title-menu'> Menu </title>
                <desc id='desc-menu'> Menu Icon to Home, Notes and Photos</desc>
              <g>
              <path d="M160 153.3c0 3.7-3 6.7-6.7 6.7h-50.5c-3.7 0-6.7-3-6.7-6.7v-50.5c0-3.7 3-6.7 6.7-6.7h50.5c3.7 0 6.7 3 6.7 6.7v50.5zM288 153.3c0 3.7-3 6.7-6.7 6.7h-50.5c-3.7 0-6.7-3-6.7-6.7v-50.5c0-3.7 3-6.7 6.7-6.7h50.5c3.7 0 6.7 3 6.7 6.7v50.5zM416 153.3c0 3.7-3 6.7-6.7 6.7h-50.5c-3.7 0-6.7-3-6.7-6.7v-50.5c0-3.7 3-6.7 6.7-6.7h50.5c3.7 0 6.7 3 6.7 6.7v50.5z"></path><g><path d="M160 281.3c0 3.7-3 6.7-6.7 6.7h-50.5c-3.7 0-6.7-3-6.7-6.7v-50.5c0-3.7 3-6.7 6.7-6.7h50.5c3.7 0 6.7 3 6.7 6.7v50.5zM288 281.3c0 3.7-3 6.7-6.7 6.7h-50.5c-3.7 0-6.7-3-6.7-6.7v-50.5c0-3.7 3-6.7 6.7-6.7h50.5c3.7 0 6.7 3 6.7 6.7v50.5zM416 281.3c0 3.7-3 6.7-6.7 6.7h-50.5c-3.7 0-6.7-3-6.7-6.7v-50.5c0-3.7 3-6.7 6.7-6.7h50.5c3.7 0 6.7 3 6.7 6.7v50.5z"></path></g><g><path d="M160 409.3c0 3.7-3 6.7-6.7 6.7h-50.5c-3.7 0-6.7-3-6.7-6.7v-50.5c0-3.7 3-6.7 6.7-6.7h50.5c3.7 0 6.7 3 6.7 6.7v50.5zM288 409.3c0 3.7-3 6.7-6.7 6.7h-50.5c-3.7 0-6.7-3-6.7-6.7v-50.5c0-3.7 3-6.7 6.7-6.7h50.5c3.7 0 6.7 3 6.7 6.7v50.5zM416 409.3c0 3.7-3 6.7-6.7 6.7h-50.5c-3.7 0-6.7-3-6.7-6.7v-50.5c0-3.7 3-6.7 6.7-6.7h50.5c3.7 0 6.7 3 6.7 6.7v50.5z"></path></g>
            </button>
            </g>
            </svg>
            <div class='profile-name'>
              <h4><strong>{{view_user.get_header}}</strong></h4>
            </div>
        </div>
      <div class="collapse navbar-collapse" id="nav-portfolio-container">
          <div class='row'>
              <ul class='nav nav-portfolio navbar-right navbar-nav text-center' >
               <li><a href='{{view_user.get_absolute_url}}' class='home'><strong>HOME</strong></a></li>
               <li><a href = '{% url "notes:view_notes" username=view_user.username %}' class='notes'><strong>NOTES</strong></a></li>
               <li><a href = '{% url "album:view_album" username=view_user.username %}' class='album'><strong>PHOTOS</strong></a></li>
              </ul>
          </div>
      </div>
    </div>
</nav>


{% block portfolio-body%}
{% endblock %}

</div>
{% endblock %}